### ISSUE TITLE
Error on blinky example [MacOS]

### ISSUE THREAD

**Issue by MikeGlennFWC** [jannic/rp-microcontroller-rs#3]
Hi,

I've tried to build the simple blinky example on an Intel Mac, i get the following error message

```bash
error: failed to run custom build command for `rp-pico v0.1.2 (/Users/mike/rp-microcontroller-rs/boards/rp-pico)`

Caused by:
  process didn't exit successfully: `/Users/mike/rp-microcontroller-rs/boards/rp-pico/target/release/build/rp-pico-e40bae595826af2c/build-script-build` (exit code: 1)
  --- stdout
  cargo:rustc-link-search=/Users/mike/rp-microcontroller-rs/boards/rp-pico/target/thumbv6m-none-eabi/release/build/rp-pico-ab0cb9379176bdff/out
  TARGET = Some("thumbv6m-none-eabi")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-apple-darwin")
  CC_thumbv6m-none-eabi = None
  CC_thumbv6m_none_eabi = None
  TARGET_CC = None
  CC = None
  CROSS_COMPILE = None
  CFLAGS_thumbv6m-none-eabi = None
  CFLAGS_thumbv6m_none_eabi = None
  TARGET_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = None
  running: "arm-none-eabi-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-mthumb" "-march=armv6s-m" "-Wall" "-Wextra" "-o" "/Users/mike/rp-microcontroller-rs/boards/rp-pico/target/thumbv6m-none-eabi/release/build/rp-pico-ab0cb9379176bdff/out/src/bs2_default_padded_checksummed.o" "-c" "src/bs2_default_padded_checksummed.S"

  --- stderr


  error occurred: Failed to find tool. Is `arm-none-eabi-gcc` installed?


warning: build failed, waiting for other jobs to finish...
error: build failed
```

I also initially encountered missing "thumbv6m-none-eabi" - i solved this by doing

```rustup target add thumbv6m-none-eabi```

It may be worth adding this step to the readme

**Comment by jannic** [comment]
Hi!
That's because of the build-dependency on the `cc` crate. You probably want to install it when developing for the Rasperry Pi Pico.
However, I don't know how to do it on MacOS. On Linux (Debian or Ubuntu) you could install it with `apt-get install gcc-arm-none-eabi`.
For now, I changed the crate to directly include a pre-compiled binary bootloader. So it should work without `gcc`.

When you develop for an arm micro-controller, I guess sooner or later you'll encounter another crate needing it. So it's probably still a good idea to find out how to install it on MacOS.
